# =========================================================== Sample scenario generated by Specflow
Feature: SpecflowExamples
	In order to avoid silly mistakes
	As a math idiot
	I want to be told the sum of two numbers

@mytag
Scenario: Add two numbers
	Given I have entered 50 into the calculator
	And I have entered 70 into the calculator
	When I press add
	Then the result should be 120 on the screen


# =========================================================== Custom scenario with a single parameter
Scenario Outline: Login – works on every page
Given I am on the <Page> page
When I login with default user
Then I am successfully logged in

Examples:
| Page         |
| Home         |
| Article list |
| Article      |
| Checkout     |
| Confirmation |

# =========================================================== Custom scenario with multiple parameter
Scenario Outline: Login – works on every page with custom login
Given I am on the <Page> page
When I login with the following user
	| Email               | Password |
	| successkid@meme.com | admin123 |
Then I am successfully logged in

Examples:
| Page         |
| Home         |
| Article list |
| Article      |
| Checkout     |
| Confirmation |